import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Background from '../components/ui/animated-grid-pattern';
import Profile from './profile';
import Path from '@/components/ui/path';


const Roberto = localFont({
	src: [
		{
			path: 'fonts/Roberto/RobertoSans-Bold.ttf',
			weight: '700',
			style: 'bold',
		},
		{
			path: 'fonts/Roberto/RobertoSans-Medium.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Roberto/RobertoSans-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-roberto',
});

const Degular = localFont({
	src: [
		{
			path: 'fonts/Degular/Degular-Bold.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Degular/Degular-Black.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Degular/Degular-Medium.otf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-degular',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const currentYear = new Date().getFullYear();

	return (
		<html lang="en">
			<body className={`${Roberto.variable} ${Degular.variable} relative`}>
				<Background />
				<div className="flex px-16 gap-16">
					<div className="grid gap-8 h-full pb-12 pt-20 max-w-96">
						<Profile />
					</div>
					<div className="py-20 h-full w-full">
						<Path />
						{children}
						<div className="flex justify-center items-center">
							<div className="absolute bottom-8">
								<h6 className="text-base font-roberto font-light text-[#EFEFEF80] mt-8">
									Tous droits réservés - {currentYear}
								</h6>
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
