import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const Roberto = localFont({
	src: [
		{
			path: 'fonts/Roberto/RobertoSans-Bold.ttf',
			weight: '700',
			style: 'bold',
		},
		{
			path: 'fonts/Roberto/RobertoSans-Medium.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Roberto/RobertoSans-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: "--font-roberto",
})

const Degular = localFont({
	src: [
		{
			path: 'fonts/Degular/Degular-Bold.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Degular/Degular-Black.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/Degular/Degular-Medium.otf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: "--font-degular",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${Roberto.variable} ${Degular.variable}`}>
				{children}
			</body>
		</html>
	);
}
