import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const Roberto = localFont({
	src: [
		{
			path: '../public/fonts/Roberto/RobertoSans-Bold.ttf',
			weight: '400',
			style: 'normal',
		},
	],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
		</html>
	);
}
